#!/bin/bash

checkInternet()
{
  echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1 # query google with a get request
  if [ $? -eq 0 ]; then #check if the output is 0, if so no errors have occured and we have connected to google successfully
    return 0
  else
    echo "Error: no active internet connection" >&2 #sent to stderr
    return 1
  fi
}

 checkInternet || exit 1 #if no connection exit

 getword=$1+$2+$3 #get 3 parameter as input
 wordresults=$(curl -sX GET --header "Accept: application/json" "http://api.pearson.com/v2/dictionaries/entries?headword=$getword") > /dev/null 2>&1 #fetch results for input word
 count=$(echo $wordresults | jq '.count')
 worddef=null;
 
 if [ $count -gt 0 ]; then #check count of results greater than zero
    i=0;
    while [ "$worddef" == null ]; do
 	worddef=$(echo $wordresults | jq '.results['$i'].senses[].definition') #get meaning of the word
    ((i++))
 	done
    ((i--))
 	wordexample=$(echo $wordresults | jq '.results['$i'].senses[]| select(.examples != null) |.examples[].text') #get examples if exists
 
 echo
 echo '================================================================'
 echo "| Definition: $worddef"

 	if [ ! -z "$wordexample" ]; then #check if the variable is set and not empty
 		echo "| Example:    $wordexample"
 	else
 		echo "| Example:     No example found"
 	fi

 echo '================================================================'
 echo
 else
	 echo Word-not-found
 fi
 
